import { listingSlugRedirects } from "@/data/listing-slug-redirects";

export function buildCloudflareRedirects() {
  const lines = [
    "# Generated by npm run generate:redirects. Do not edit by hand.",
    "# Renamed restaurant slugs must precede the generic legacy rules."
  ];

  for (const [oldSlug, currentSlug] of Object.entries(listingSlugRedirects)) {
    const destination = `/restaurants/${currentSlug}/`;
    lines.push(
      `/listings/${oldSlug} ${destination} 301`,
      `/listings/${oldSlug}/ ${destination} 301`,
      `/restaurants/${oldSlug} ${destination} 301`,
      `/restaurants/${oldSlug}/ ${destination} 301`
    );
  }

  lines.push(
    "/listings/:slug /restaurants/:slug/ 301",
    "/listings/:slug/ /restaurants/:slug/ 301",
    "/listings /restaurants/ 301",
    "/listings/ /restaurants/ 301"
  );

  return `${lines.join("\n")}\n`;
}
