export const importRoleOptions = [
  "ignore",
  "name",
  "slug",
  "category",
  "typeFilter",
  "area",
  "neighborhood",
  "address",
  "phone",
  "website",
  "email",
  "image",
  "rating",
  "reviews",
  "price",
  "description",
  "mapReviewLink",
  "rawFeatureJson",
  "city",
  "postcode",
  "latitude",
  "longitude",
  "logo",
  "dedupeId",
  "sourceStatus",
  "workingHours",
  "verified",
  "actionLink"
] as const;

export type ImportFieldRole = (typeof importRoleOptions)[number];

export const importRoleLabels: Record<ImportFieldRole, string> = {
  ignore: "Ignore",
  name: "Listing name",
  slug: "Slug/source ID",
  category: "Category",
  typeFilter: "Type/filter",
  area: "Area",
  neighborhood: "Neighborhood",
  address: "Address/location",
  phone: "Phone/contact",
  website: "Website/social",
  email: "Email",
  image: "Image/media",
  rating: "Rating",
  reviews: "Reviews",
  price: "Price",
  description: "Description",
  mapReviewLink: "Map/review link",
  rawFeatureJson: "Raw feature JSON",
  city: "City",
  postcode: "Postcode",
  latitude: "Latitude",
  longitude: "Longitude",
  logo: "Logo",
  dedupeId: "Dedupe/source ID",
  sourceStatus: "Business status",
  workingHours: "Opening hours",
  verified: "Verified profile",
  actionLink: "Action link"
};
